dist: bionic
language: python

python:
  - '3.9'

addons:
  chrome: stable

branches:
  only:
    - main

install:
  - pip install -r requirements.txt

env:
  global:
    - DJANGO_SETTINGS_MODULE="pureBeurre.settings.travis"

services:
  - postgresql

script:
  - pytest
