sudo: required
dist: bionic
language: python

python:
  - '3.9'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

branches:
  only:
    - main

install:
  - pip install -r requirements.txt
  - sudo wget -N https://chromedriver.storage.googleapis.com/97.0.4692.36/chromedriver_linux64.zip -P ~/
  - sudo unzip ~/chromedriver_linux64.zip -d ~/
  - sudo rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver  /home/travis/virtualenv/python3.9.7/tests/tests_functionnal
  - sudo chmod +x /home/travis/virtualenv/python3.9.7/tests/tests_functionnal/chromedriver

env:
  global:
    - DJANGO_SETTINGS_MODULE="pureBeurre.settings.travis"

services:
  - postgresql

script:
  - pytest
