dist: bionic
language: python

python:
  - '3.9'

addons:
  chrome: stable

branches:
  only:
    - main
    
install:
  - pip install -r requirements.txt

before_script:
  - install-webdrivers --path webdrivers

env:
  global:
    - DJANGO_SETTINGS_MODULE="config.settings.travis"

services:
  - postgresql

script:
  - pytest