dist: focal
language: python

python:
  - '3.9'

addons:
  apt:
    sources:
      - sourceline: 'ppa:chris-lea/redis-server'
    packages:
    - redis-tools
    - redis-server

  chrome: stable

branches:
  only:
    - main
    
install:
  - sudo apt install cloud-init
  - pip install -r requirements.txt

before_script:
  - install-webdrivers --path webdrivers

env:
  global:
    - DJANGO_SETTINGS_MODULE="config.settings.travis"

services:
  - postgresql

script:
  - pytest